---
title: "equivalance testing"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(latex2exp)
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")),fig.width = 10, fig.height = 5,
                      warning = FALSE, message = FALSE, error = FALSE)
library(patchwork)
library(tidyverse)
library(GGally)
library(ggtext)
library(sasLM)
library(janitor)
library(car)
library(broom)
library(ggpubr)
library(rstatix)
library(readxl)
library(sf)
library(lme4)
library(resourceviz)
library(extrafont)
thematic::thematic_on(font = 'Calibri')
source('utils.R')
library(jtools)
library(robustlmm)
library(lme4)
library(TOSTER)
library(lmerTest)
```


## Equivalence testing



```{r}


#get means for bankfull width

bf_means <- emmeans(rlmm_bf, specs = 'mgmt')
m1 <- exp(2.12)
m2 <- exp(2.15)
sd1 <- exp(0.0306)
sd2 <- exp(0.0325)

TOSTtwo.raw(m1 = m1,
            m2 = m2, 
            sd1 = sd1,
            sd2 = sd2,
            n1 = 189,
            n2 = 116,
            low_eqbound = -.35,
            high_eqbound = .35,
            alpha = 0.05, 
            var.equal = F)

    TOSTtwo(m1 = m1,
            m2 = m2, 
            sd1 = sd1,
            sd2 = sd2,
            n1 = 189,
            n2 = 116,
            low_eqbound_d = -.5,
            high_eqbound_d = .5,
            alpha = 0.05, 
            var.equal = F)

```



